// <auto-generated />
namespace ChampionMains.Pyrobot.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class subredditsettings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(subredditsettings));
        
        string IMigrationMetadata.Id
        {
            get { return "201606260449096_subreddit-settings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
