// <auto-generated />
namespace ChampionMains.Pyrobot.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class summonerchampionmaxter_ix_summoner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(summonerchampionmaxter_ix_summoner));
        
        string IMigrationMetadata.Id
        {
            get { return "201608081849596_summonerchampionmaxter_ix_summoner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
