// <auto-generated />
namespace ChampionMains.Pyrobot.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class subredditemojicreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(subredditemojicreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201909020749505_subredditemoji-create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
