// <auto-generated />
namespace ChampionMains.Pyrobot.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class subredditrenamemissingadmintomissingmod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(subredditrenamemissingadmintomissingmod));
        
        string IMigrationMetadata.Id
        {
            get { return "201908312109104_subreddit-rename-missingadmin-to-missingmod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
